classdef RJMCMC
    properties
        m       % (scalar) maximum number of regressors available
        k       % (scalar) number of observations
        mu_b    % (scalar) mean of the true coefficients
        sigma_p % (scalar) randomness in the coefficients
        sigma_0 % (scalar) noise in y
        sigma_r % (scalar) randomness in the drawn coefficients 
        R       % (scalar) number of draws / iterations
        %%% generated by DGP %%%
        n0      % (scalar) true number of regressors
        b       % (n0 * 1) true coefficients
        X       % (k * m) regressors
        Y       % (k * 1) response
        %%% store the results for each draw %%%
        n       % (1 * R) number of selected regressors
        bn      % (m * R) coefficients
    end
    methods 
        function [dt] = DGP(dt)
            % n0 ~ DiscreteUniform(1, m)
            dt.n0 = ceil(rand(1) * dt.m);

            % b ~ N(mu_b, sigma_p^2)
            dt.b = dt.mu_b + dt.sigma_p * randn(dt.n0, 1); 

            % X ~ 5 * N(0, 1) 
            dt.X = 5 * randn(dt.k, dt.m); 

            % e ~ N(0, sigma_0^2)
            e = dt.sigma_0 * randn(dt.k, 1);

            % Y = X * b + e
            % X is only selected first n0 columns
            dt.Y = dt.X(:, 1:dt.n0) * dt.b + e;
        end    
        function [dt] = fit(dt)
            % initialization
            dt.n(1) = ceil(rand(1) * dt.m);
            dt.bn(:, 1) = dt.mu_b + dt.sigma_p * randn(dt.n(1), 1);

            for r = 2:dt.R
                n_past  = dt.n(r - 1);
                bn_past = dt.bn(1:n_past, r - 1);

                n_star = ceil(rand(1) * dt.m);

                if n_star >= n_past
                    u = dt.sigma_r * randn(n_star, 1);
                    bn_star = [bn_past; zeros(n_star - n_past, 1)] + u; 
                    h1 = prod(normpdf(u, 0, dt.sigma_r));
                    h2 = prod(normpdf(u(1:n_past), 0, dt.sigma_r));
                else % n_star < n_past
                    u1 = dt.sigma_r * randn(n_star, 1);
                    u2 = bn_past(n_star+1:end);
                    u  = [u1; u2];
                    bn_star = bn_past(1:n_star) + u1;
                    h1 = prod(normpdf(u1, 0, dt.sigma_r));
                    h2 = prod(normpdf(u, 0, dt.sigma_r));
                end    

                % update ratio
                E1 = norm(dt.Y - dt.X(:, 1:n_star) * bn_star)^2 / (2 * dt.sigma_0^2);
                E2 = norm(dt.Y - dt.X(:, 1:n_past) * bn_past)^2 / (2 * dt.sigma_0^2); 

                t1 = (2 * pi * dt.sigma_p^2)^((n_past - n_star) / 2);
                t2 = exp(-1 / (2 * dt.sigma_p^2) * (norm(bn_star - dt.mu_b)^2 - norm(bn_past - dt.mu_b)^2));

                rho = min(exp(-E1 + E2) * t1 * t2 * h2 / h1, 1);

                if rand(1) < rho
                    dt.n(r)            = n_star;
                    dt.bn(1:n_star, r) = bn_star;
                else
                    dt.n(r)            = n_past;
                    dt.bn(1:n_past, r) = bn_past;
                end    
            end  
        end 
        function [] = plot_hist(dt, savename)
            fig = figure;

            histogram(dt.n, 'Normalization', 'pdf', 'FaceAlpha', 0.5);
            xlim([0.5 10.5]);
            ylim([0 1]);

            xlabel('$n$', 'Interpreter', 'latex');
            ylabel('Density', 'Interpreter', 'latex');
            title(sprintf('True number of regressors $n_0 = %d$', dt.n0), 'Interpreter', 'latex');

            saveas(fig, savename, 'epsc');
            close(fig);
        end  
        function [] = plot_path(dt, savename)
            fig = figure;

            plot(dt.n);
            ylim([0 10]);

            xlabel('Iteration', 'Interpreter', 'latex');
            ylabel('Number of selected regressors', 'Interpreter', 'latex');
            title(sprintf('True number of regressors $n_0 = %d$', dt.n0), 'Interpreter', 'latex');

            saveas(fig, savename, 'epsc');
            close(fig);
        end    
    end    
end
